spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

jwt:
  secret: Ymx1ZWtub3Rpc2ZhbGxpbmdpd2FzaG9sZGluZ29uZm9yeW91

mail:
  host: smtp.gmail.com
  port: 587
  username: "weecostep@gmail.com"
  password: "sksy oxno tlji tkbb"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000
