spring:
  datasource:
    url: jdbc:mysql://ecostep-db.cruikuqa2yrq.ap-northeast-2.rds.amazonaws.com:3306/ecostep_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: kyuwon
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  profiles:
    active: default

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

mail:
  host: smtp.gmail.com
  port: 587
  username: "weecostep@gmail.com"
  password: "sksy oxno tlji tkbb"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000

server:
  port: 80