spring:
  datasource:
    url: jdbc:mysql://ecostepdb.cruikuqa2yrq.ap-northeast-2.rds.amazonaws.com:3306/ecostep?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kyuwon
    password: ${DB_PASSWORD}
    driver-class-name=com: mysql.jdbc

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  profiles:
    active: default

jwt:
  secret: ${JWT_SECRET}

mail:
  host: smtp.gmail.com
  port: 587
  username: "weecostep@gmail.com"
  password: "sksy oxno tlji tkbb"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000
